language: python
python:
  - "3.6"

script:
  - echo "insert tests here"
  
deploy:
  provider: script
  script: bash -x deploy.sh

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4449f3d4ac41c2dd7691
    on_success: change
    on_failure: always
    on_start: never
