matrix:
  include:
    - language: python
      python:
        - "3.6"
      script:
        - echo "insert tests here"
      deploy:
        provider: script
        script: bash -x deploy.sh
    - language: ruby
      rvm:
        - 2.4
      install:
        - gem install github-pages
        - gem install html-proofer
      script:
        - cd docs/
        - bundle exec jekyll build --future
        - bundle exec htmlproofer ./_site --only-4xx --check-favicon --check-html
      env:
        global:
          - NOKOGIRI_USE_SYSTEM_LIBRARIES=true


notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f694e2f80d5bba482051
    on_success: always
    on_failure: always
    on_start: never
