language: python
python:
  - "3.6"

script:
  - echo "insert tests here"
  
deploy:
  provider: script
  script: bash -x deploy.sh

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1612037f1280054d7b63
    on_success: always
    on_failure: always
    on_start: never
